---
title: "Column & Row Basic Operation of Dataframe"
output:
  html_document:
    df_print: paged
---

# Declare dataframe for testing
```{r message = FALSE}
library(dplyr)

ORG_DF<-data.frame(C1=c(1,2,3), C2=c(4,5,6), C3=c(6,7,8), 
                   row.names = c('R1', 'R2', 'R3'))
ORG_DF
```

# 1. Column Operation

## 1-1. Deletion
```{r}
temp_df<-ORG_DF

temp_df['C1']<-NULL
temp_df['C2']<-NULL

# Other ways
## temp_df$C1<-NULL
## temp_df$C2<-NULL
## temp_df<-temp_df[-c(1,2)]
## temp_df<-select(temp_df, -C1, -C2)
## temp_df<-select(temp_df, -1, -2)
## temp_df<-subset(temp_df, select = -c(C1, C2))
## temp_df<-subset(temp_df, select = -c(1, 2))

temp_df

```


## 1-2. Addition
```{r}
temp_df<-ORG_DF

temp_df['C4']<-10
temp_df['C5']<-c(1,2,3)
temp_df['C6']<-temp_df['C1']+temp_df['C2']


# Other ways
## temp_df$C4<-10
## temp_df$C5<-c(1,2,3)
## temp_df$C6<-temp_df$C1+temp_df$C2
## temp_df<-mutate(temp_df, C4=1, C5=c(1,2,3), C6=C1+C2)

temp_df
```


## 1-3. Selection
### 1-3-2 Single
```{r}
temp_df<-ORG_DF

temp_df<-ORG_DF['C2']

# Other ways
## temp_df<-ORG_DF[2]
## temp_df<-ORG_DF[,2] # WRANING!! return vector
## temp_df<-ORG_DF$C2 # WRANING!! return vector

temp_df
```


### 1-3-2. Multiple
```{r}
temp_df<-ORG_DF

temp_df<-ORG_DF[c('C1', 'C2')]

# Other ways
## ORG_DF[c(1,2)]
## select(ORG_DF, C1, C2)
## select(ORG_DF, 'C1', 'C2')
## select(ORG_DF, 1, 2)
## subset(ORG_DF, select = c(C1, C2))
## subset(ORG_DF, select = c(1, 2))

temp_df
```


## 1-4. Rename
```{r}
temp_df<-ORG_DF

colnames(temp_df)<-c('C1', 'C2', 'NEW_C3')

# Other ways
## temp_df<-temp_df %>% `colnames<-`(c('C1', 'C2', 'NEW_C3'))
## temp_df<-rename(temp_df, NEW_C3=C3)

temp_df
```


## 1-5. Order
```{r}
temp_df<-ORG_DF

temp_df<-select(temp_df, C3, everything())

temp_df
```


# 2. Row Opertaions

## 2-1. Selection
```{r}
temp_df<-temp_df[c(2,3),]

# Other ways
## temp_df[c('R1', 'R2'),]
## temp_df[c(TRUE, FALSE, FALSE),]
## slice(temp_df, c(1, 2))

temp_df
```

# 2-2. Deletion
```{r}
temp_df<-temp_df[-c(2,3),]

# Other ways
## temp_df<-temp_df[!rownames(temp_df) %in% c('R2', 'R3')]
## temp_df<-slice(temp_df, -c(2, 3))
## temp_df<-slice(temp_df, !rownames(temp_df) %in% c('R2', 'R3'))

temp_df

```


## 2-3. Addition
```{r}
temp_df<-ORG_DF

temp_df<-rbind(temp_df, temp_df)

temp_df
```


## 2-4. Rename
```{r}
temp_df<-ORG_DF

rownames(temp_df)<-c('R1', 'R2', 'NEW_R3')

# Other ways
## temp_df %>% `rownames<-`(c('R1', 'R2', 'NEW_R3'))

temp_df

```
